# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy the project files
COPY . /app

# Upgrade pip and install the project dependencies
RUN python -m pip install --upgrade pip \
    && python -m pip install .

# Expose any required ports if needed (not necessary for stdio based MCP)

# Command to run the MCP server
CMD ["python", "main.py"]
