server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#  security:
#    user:
#      name: username
#      password: passw0rd


management:
  endpoints:
    web:
      exposure:
        include: "*"