[package]
name = "web_input_name"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }