spring.application.name=springai-pgvector_insert
spring.sql.init.mode=always
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=text-embedding-ada-002



spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=true