service: serverless-offline-plugins-service
farmeworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  state: dev
  region: ap-northeast-2
  environment:
    TABLE_NAME: ${self:resources.Resources.foodTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    start: 8000
    inMemory: true
    migrate: true
functions:
  create:
    handler: create.handler
    events:
      - http:
          path: /food/{name}/{description}
          method: post
          cors: true
resources:
  Resources:
    foodTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: foodTable-serverless-plugins
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5