spring.application.name=pspringai-mongodb-vector-demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=springaivectordb

spring.ai.vectorstore.mongodb.collection-name=vector_store
spring.ai.vectorstore.mongodb.initialize-schema=true
spring.ai.vectorstore.mongodb.path-name=embedding
spring.ai.vectorstore.mongodb.indexName=vector_index