name: dart_neural_network
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  matrix2d: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
