---
  - name: Install Redis
    apt: name=redis-server=2:2.8.4-2 state=present

  - name: Bind to all Interfaces
    lineinfile: dest=/etc/redis/redis.conf regexp=^bind line='bind 0.0.0.0'
    register: redisconf

  - name: Redis Started
    service: name=redis-server state=started enabled=yes

  - name: Redis Restarted
    service: name=redis-server state=restarted
    when: redisconf.changed
