# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import kilogram.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=kilogram.models.user_path),
        ),
    ]
