spring.application.name=springai_chat_memory_mysql
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:mysql://localhost:3306/springai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.ai.chat.memory.repository.jdbc.schema=classpath:schema-mysql.sql

spring.ai.chat.memory.repository.jdbc.initialize-schema=always