spring.application.name=springai-qdrant-vector-search-demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vector_store
spring.ai.vectorstore.qdrant.initialize-schema=true