spring:
  application:
    name: greeting-kafka-streams
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:19092
    streams:
      bootstrap-servers: localhost:19092
      application-id: greeting-kafka-streams
    properties:
      default:
        deserialization:
          exception:
            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler


