spring.application.name=springai-chromadb-demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000

spring.ai.vectorstore.chroma.collection-name=SpringAiCollection
spring.ai.vectorstore.chroma.initialize-schema=true