spring:
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: mySch-
  #  task:
  #    execution:
  #      thread-name-prefix: myTask-
  #    scheduling:
  #      thread-name-prefix: myScheduler-
  #  main:
  #    keep-alive: true