apiVersion: v1
kind: Service

metadata:
  name: nest-server

spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 3000
      targetPort: 3000
