service: serverless-store

custom:
  cognitoAuthorizer: arn:aws:cognito-idp:ap-northeast-2:367416660003:userpool/ap-northeast-2_YXaBTXrJm

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
      Resource: [
        "arn:aws:dynamodb:ap-northeast-2:*:table/Products",
        "arn:aws:dynamodb:ap-northeast-2:*:table/ShoppingCart"
      ]

functions:
  products:
    handler: functions/products.handler
    events:
      - http: GET products
      - http:
          method: GET
          path: productsAuth
          authorizer: 
            arn: ${self:custom.cognitoAuthorizer}          
      - http: OPTIONS productsAuth    
      - http:
          method: POST
          path: cart
          authorizer: 
            arn: ${self:custom.cognitoAuthorizer}
      - http: OPTIONS cart
      - http:
          method: PUT
          path: checkout
          authorizer: 
            arn: ${self:custom.cognitoAuthorizer}
      - http: OPTIONS checkout  
