service: serverless-store

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  region: ap-northeast-2

functions:
  products:
    handler: functions/products.handler
    events:
      - http: GET products
      - http: POST cart
      - http: OPTIONS cart      
      - http: PUT checkout
      - http: OPTIONS checkout
