name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.2
  bootpay: ^4.4.5
  bootpay_webview_flutter_wkwebview: 3.13.15
  dart_code_metrics: ^5.7.5
  dio: ^5.3.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^9.0.3
  injectable: ^2.1.2
  intl:
  json_annotation: ^4.8.1
  kakao_flutter_sdk_user:
  logger: ^1.4.0
  lottie:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mocktail: ^1.0.0
  retrofit: ^4.0.1
  stream_transform: ^2.1.0

dependency_overrides:
  win32: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/lottie/
    - assets/env/