spring.application.name=springai_chat_memory_jdbc
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.ai.chat.memory.repository.jdbc.schema=classpath:schema-h2.sql
