version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: slack
    ports:
      - "3030:5432"
  web:
    image: slack-clone-server
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["node", "index.js"]
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8081:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet: