name: egghead_getstarted_dart
description: My First Dart Project
version: 0.1.0
author: neverlish

dependencies:
  path: '^1.6.2'
  mock_data: '^1.2.0'

dev_dependencies:
  test: ^1.5.0

environment:
  sdk: '>=2.1.0 <3.0.0'