# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android doAdd commentMore actions
  desc "Submit a new version to the internal testing track"
  lane :beta do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )
  end

  desc "Submit a new version to the production"
  lane :release do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'production'
    )
  end
end