Resources:
  HelloLambdaServiceRoleE071F162:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TodoAppStack/HelloLambda/ServiceRole/Resource
  HelloLambda3D9C82D6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767S3BucketE3DCFB23
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767S3VersionKey3B1EB1E8
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767S3VersionKey3B1EB1E8
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - HelloLambdaServiceRoleE071F162
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          isProduction: absolutely not
      MemorySize: 256
      Timeout: 10
    DependsOn:
      - HelloLambdaServiceRoleE071F162
    Metadata:
      aws:cdk:path: TodoAppStack/HelloLambda/Resource
      aws:asset:path: /Users/hyeonjinho/Desktop/dev/Learned/aws/egghead-build-app-aws-cdk/lambda
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Account
  EndpointDeployment318525DA64a67e8e315d56ab1175a4fe5a15dd89:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DA64a67e8e315d56ab1175a4fe5a15dd89
      StageName: prod
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionTodoAppStackEndpointCF9D4237ANYproxyD9736D9C:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.TodoAppStackEndpointCF9D4237.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestTodoAppStackEndpointCF9D4237ANYproxy530847FD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.TodoAppStackEndpointCF9D4237.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloLambda3D9C82D6
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionTodoAppStackEndpointCF9D4237ANY54A066B0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/ANY/ApiPermission.TodoAppStackEndpointCF9D4237.ANY..
  EndpointANYApiPermissionTestTodoAppStackEndpointCF9D4237ANY215AB9B4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/ANY/ApiPermission.Test.TodoAppStackEndpointCF9D4237.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloLambda3D9C82D6
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: TodoAppStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.60.0,@aws-cdk/assets=1.60.0,@aws-cdk/aws-apigateway=1.60.0,@aws-cdk/aws-applicationautoscaling=1.60.0,@aws-cdk/aws-autoscaling-common=1.60.0,@aws-cdk/aws-cloudwatch=1.60.0,@aws-cdk/aws-codeguruprofiler=1.60.0,@aws-cdk/aws-ec2=1.60.0,@aws-cdk/aws-events=1.60.0,@aws-cdk/aws-iam=1.60.0,@aws-cdk/aws-kms=1.60.0,@aws-cdk/aws-lambda=1.60.0,@aws-cdk/aws-logs=1.60.0,@aws-cdk/aws-s3=1.60.0,@aws-cdk/aws-s3-assets=1.60.0,@aws-cdk/aws-sqs=1.60.0,@aws-cdk/aws-ssm=1.60.0,@aws-cdk/cloud-assembly-schema=1.60.0,@aws-cdk/core=1.60.0,@aws-cdk/cx-api=1.60.0,@aws-cdk/region-info=1.60.0,jsii-runtime=node.js/v12.18.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767S3BucketE3DCFB23:
    Type: String
    Description: S3 bucket for asset "c03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767"
  AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767S3VersionKey3B1EB1E8:
    Type: String
    Description: S3 key for asset version "c03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767"
  AssetParametersc03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767ArtifactHash8CCB462B:
    Type: String
    Description: Artifact hash for asset "c03e598371ffce3adc2917c801de627a1b28dffc5973502e503f8cd09c2d2767"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

