name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ">=7.0.0 <9.0.0"
  http: ^1.0.0

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  mockito: ^5.4.2
  build_runner: ^2.4.5

# temp: dependency 버전 충돌 방지
dependency_overrides:
  test_api: 0.5.2
  matcher: ^0.12.13

flutter:
  uses-material-design: true
