// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7NWsAUvlkEbMjgH-XrYjZBqh3abob2g',
    appId: '1:242784285519:web:9a4acc182e4ab8e26b4b3a',
    messagingSenderId: '242784285519',
    projectId: 'fb-auth-provider-17da4',
    authDomain: 'fb-auth-provider-17da4.firebaseapp.com',
    storageBucket: 'fb-auth-provider-17da4.appspot.com',
    measurementId: 'G-7FEH31P2FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-3eCHvBHc8C7e4a3zmX3y0nus_XcOBs',
    appId: '1:242784285519:android:3730a1be5d856f076b4b3a',
    messagingSenderId: '242784285519',
    projectId: 'fb-auth-provider-17da4',
    storageBucket: 'fb-auth-provider-17da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvtkMEWvNfslQVTwla6nTr6ES6rr3WcQ',
    appId: '1:242784285519:ios:00cf31d5c3da03706b4b3a',
    messagingSenderId: '242784285519',
    projectId: 'fb-auth-provider-17da4',
    storageBucket: 'fb-auth-provider-17da4.appspot.com',
    iosBundleId: 'com.example.fbAuthProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvtkMEWvNfslQVTwla6nTr6ES6rr3WcQ',
    appId: '1:242784285519:ios:0063abed798c308b6b4b3a',
    messagingSenderId: '242784285519',
    projectId: 'fb-auth-provider-17da4',
    storageBucket: 'fb-auth-provider-17da4.appspot.com',
    iosBundleId: 'com.example.fbAuthProvider.RunnerTests',
  );
}
