// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5_Z2moZ_vK_rUQRjFwLNyrJCHKyG1zc',
    appId: '1:836707899447:web:f7db6d35a975003ebb87b2',
    messagingSenderId: '836707899447',
    projectId: 'netflix-clone-test-30a61',
    authDomain: 'netflix-clone-test-30a61.firebaseapp.com',
    storageBucket: 'netflix-clone-test-30a61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpIH_D7iPPQ7cvAx0VaMv_8fJbZcVEJ4',
    appId: '1:836707899447:android:c4ec4e01a67360cbbb87b2',
    messagingSenderId: '836707899447',
    projectId: 'netflix-clone-test-30a61',
    storageBucket: 'netflix-clone-test-30a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLB1Kk729kgdU7JfCGfbtPuYP4QAJe-4',
    appId: '1:836707899447:ios:694f0c330cca69c0bb87b2',
    messagingSenderId: '836707899447',
    projectId: 'netflix-clone-test-30a61',
    storageBucket: 'netflix-clone-test-30a61.appspot.com',
    iosClientId: '836707899447-pg5hev1gs98qiuu71j6p60842avdtmrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACLB1Kk729kgdU7JfCGfbtPuYP4QAJe-4',
    appId: '1:836707899447:ios:82cf5bb36ccc2fc5bb87b2',
    messagingSenderId: '836707899447',
    projectId: 'netflix-clone-test-30a61',
    storageBucket: 'netflix-clone-test-30a61.appspot.com',
    iosClientId: '836707899447-lh28s2p3a77jd42jf5m8ah9fivvsq7vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixClone.RunnerTests',
  );
}
